export const adjectives = [
    "box",
    "oval",
    "longing",
    "sophisticated",
    "spare",
    "numberless",
    "lonely",
    "crowd",
    "fail",
    "cemetery"       ,
    "battle",
    "crate",
    "wide",
    "coach",
    "slap",
    "cat",
    "continue"       ,
    "property"       ,
    "giants",
    "wipe",
    "wandering"      ,
    "unnatural"      ,
    "wander"     ,
    "invincible",
    "coil",
    "ring",
    "nerve",
    "picture",
    "guard",
    "possessive"     ,
    "industry",
    "suit",
    "price",
    "fantastic",
    "hang",
    "arm",
    "unit",
    "mourn",
    "hope",
    "yak",
    "flesh",
    "tart",
    "knotty"     ,
    "earsplitting",
    "tire",
    "able",
    "contain",
    "blind",
    "elite",
    "magenta",
    "pop",
    "bridge",
    "earn",
    "call",
    "premium"        ,
    "warlike",
    "fixed",
    "bit",
    "attract"        ,
    "lumber"     ,
    "strong"     ,
    "belligerent"        ,
    "condemned"      ,
    "attempt"        ,
    "expand",
    "ask",
    "change",
    "sick",
    "tree",
    "tested",
    "kind",
    "quarter",
    "soft",
    "repulsive"      ,
    "dynamic"        ,
    "dinner"     ,
    "calculate"      ,
    "accessible",
    "stone",
    "envious"        ,
    "island",
    "saw",
    "minor",
    "shade",
    "handy",
    "thankful"       ,
    "maniacal",
    "stop",
    "vivacious",
    "curve",
    "note",
    "detect",
    "boat",
    "collar",
    "true",
    "doubt",
    "quixotic"       ,
    "reason"     ,
    "business"       ,
    "squeamish",
    "crawl",
    "woozy",
    "air",
    "boil",
    "husky",
    "goofy",
    "wind",
    "pen",
    "advertisement"      ,
    "attack"     ,
    "existence"      ,
    "wide-eyed",
    "lazy",
    "swift",
    "yarn",
    "clean",
    "excite"     ,
    "jumbled",
    "ants",
    "frame",
    "normal",
    "mom",
    "lunch",
    "competition",
    "hat",
    "fear",
    "trouble"        ,
    "macabre",
    "hands",
    "grate",
    "thaw",
    "absorbed"       ,
    "imagine",
    "ruin",
    "icicle"     ,
    "ignorant"       ,
    "learned"        ,
    "gigantic",
    "ritzy",
    "damp",
    "motionless",
    "enter",
    "flower"     ,
    "muddled"        ,
    "long-term"      ,
    "frequent",
    "blue",
    "bewildered"     ,
    "gather"     ,
    "breakable"      ,
    "creature"       ,
    "mighty",
    "strap",
    "rhetorical"     ,
    "present"        ,
    "relieved",
    "smash",
    "liquid",
    "mushy",
    "farm",
    "erect",
    "selfish"        ,
    "chubby",
    "jog",
    "roll",
    "violet"     ,
    "throat"     ,
    "basket",
    "wise",
    "breezy",
    "awake",
    "tease",
    "hulking"        ,
    "energetic",
    "stage",
    "savory"     ,
    "popcorn"        ,
    "gifted",
    "argue",
    "floor",
    "abundant",
    "frame",
    "trade",
    "raspy",
    "limit",
    "dirt",
    "shop",
    "shop",
    "vagabond"       ,
    "bright"     ,
    "incandescent",
    "bent",
    "plastic"        ,
    "striped"        ,
    "society"        ,
    "destruction",
    "eyes",
    "silk",
    "glorious"       ,
    "scandalous",
    "sugar",
    "legs",
    "protect",
    "allow",
    "scale",
    "knowledge",
    "hope",
    "unlock",
    "pray",
    "obedient"       ,
    "support"        ,
    "payment"        ,
    "rabbit"     ,
    "rightful"       ,
    "attend",
    "clap",
    "annoyed"        ,
    "terrific"       ,
    "squeeze",
    "few",
    "nasty",
    "treat",
    "plate",
    "rob",
    "secretive"      ,
    "squash"     ,
    "complain"       ,
    "settle",
    "sofa",
    "lighten",
    "scarf",
    "deep",
    "tremble"        ,
    "scribble",
    "duck",
    "float",
    "skinny"     ,
    "terrify"        ,
    "fluffy"     ,
    "harbor",
    "work",
    "reach",
    "zinc",
    "domineering",
    "order",
    "dress",
    "hysterical",
    "face",
    "tick",
    "notice"     ,
    "substantial"        ,
    "jittery"        ,
    "person",
    "pies",
    "wish",
    "remarkable",
    "queen",
    "branch"     ,
    "expect"     ,
    "whispering",
    "faded",
    "frantic"        ,
    "preach"     ,
    "deeply"     ,
    "wiggly"     ,
    "broken"     ,
    "numerous",
    "worry",
    "vegetable",
    "found",
    "afford",
    "hover",
    "homely",
    "iron",
    "divergent",
    "wail",
    "equal",
    "future"     ,
    "hard-to-find",
    "fish",
    "dear",
    "blink",
    "country"        ,
    "screeching"     ,
    "imported"       ,
    "didactic",
    "care",
    "like",
    "thin",
    "brother",
    "time",
    "sort",
    "design",
    "milky",
    "minute"     ,
    "careless"       ,
    "knowing"        ,
    "yielding"       ,
    "direction"      ,
    "weight",
    "juice",
    "mine",
    "thirsty"        ,
    "sloppy",
    "toys",
    "pizzas",
    "foamy",
    "burly",
    "hate",
    "permit"     ,
    "interest"       ,
    "servant"        ,
    "orange"     ,
    "crowded",
    "cheer",
    "shirt",
    "observation",
    "hurry",
    "fancy",
    "trail",
    "wholesale",
    "robin",
    "slimy",
    "creator"        ,
    "cloistered"     ,
    "idiotic",
    "laugh",
    "acceptable",
    "rigid",
    "abnormal"       ,
    "grateful"       ,
    "transport"      ,
    "abiding",
    "level",
    "ancient",
    "full",
    "overt",
    "hand",
    "sock",
    "mitten"     ,
    "cluttered"      ,
    "determined",
    "pack",
    "realise"        ,
    "passenger",
    "burst",
    "ship",
    "amused"     ,
    "interesting"        ,
    "develop"        ,
    "selective"      ,
    "adjustment"     ,
    "repair"     ,
    "waggish"        ,
    "unbiased",
    "meek",
    "doctor",
    "turn",
    "decide",
    "stick",
    "careful"        ,
    "damaged",
    "eye",
    "bow",
    "moldy",
    "fat",
    "bomb",
    "snakes",
    "back",
    "mug",
    "soothe",
    "tug",
    "fire",
    "approve"        ,
    "locket"     ,
    "uneven"     ,
    "animated"       ,
    "untidy"     ,
    "please"     ,
    "pricey"     ,
    "humorous",
    "pushy",
    "available"      ,
    "smelly",
    "false",
    "scrawny"        ,
    "beginner",
    "slow",
    "heady",
    "rose",
    "marry",
    "useless"        ,
    "decisive"       ,
    "system",
    "bead",
    "obscene"        ,
    "lopsided",
    "slow",
    "violent"        ,
    "stitch"     ,
    "spiritual"      ,
    "steady"     ,
    "blue-eyed"      ,
    "mature"     ,
    "introduce"      ,
    "downtown"       ,
    "regret",
    "try",
    "righteous"      ,
    "purple"     ,
    "holistic",
    "wrist",
    "scarce",
    "lying",
    "rock",
    "cure",
    "racial",
    "happy",
    "thought"        ,
    "wrench",
    "brass",
    "chief",
    "blade",
    "toe",
    "skillful"       ,
    "purpose"        ,
    "pathetic"       ,
    "retire",
    "tap",
    "smile",
    "assorted"       ,
    "direful"        ,
    "oranges"        ,
    "hilarious"      ,
    "agreement"      ,
    "habitual"       ,
    "appliance"      ,
    "colorful"       ,
    "history"        ,
    "curtain",
    "ocean",
    "wheel",
    "paltry"     ,
    "instrument",
    "hop",
    "meddle"     ,
    "rotten",
    "fence",
    "weak",
    "cows",
    "worried"        ,
    "tightfisted",
    "flaky",
    "chunky"     ,
    "absurd",
    "dirty",
    "sound",
    "gun",
    "lowly",
    "receipt"        ,
    "teeny-tiny",
    "coat",
    "bird",
    "motion"     ,
    "combative"      ,
    "baseball",
    "key",
    "belief",
    "spoil",
    "notebook",
    "sable",
    "appreciate"     ,
    "religion",
    "wait",
    "riddle",
    "room",
    "shallow",
    "bulb",
    "way",
    "glue",
    "deserve"        ,
    "garrulous",
    "count",
    "lacking"        ,
    "valuable",
    "hook",
    "stretch"        ,
    "responsible",
    "peace",
    "rot",
    "cracker",
    "swim",
    "word",
    "sack",
    "hapless",
    "fearless",
    "scratch",
    "enjoy",
    "snow",
    "houses"     
]
export const nouns = [
    "car",
    "pear",
    "skate",
    "fork",
    "history",
    "slip",
    "hammer",
    "airplane",
    "stamp",
    "jam",
    "mother",
    "impulse",
    "tendency",
    "women",
    "force",
    "fuel",
    "horn",
    "knife",
    "stretch",
    "hands",
    "birth",
    "title",
    "birthday",
    "arm",
    "dime",
    "fly",
    "current",
    "minister",
    "argument",
    "trees",
    "friend",
    "stage",
    "town",
    "earthquake",
    "downtown",
    "run",
    "digestion",
    "tail",
    "hospital",
    "afternoon",
    "plastic",
    "produce",
    "vase",
    "children",
    "peace",
    "rule",
    "cloth",
    "judge",
    "drink",
    "grandmother",
    "wing",
    "love",
    "hobbies",
    "cause",
    "shame",
    "box",
    "punishment",
    "committee",
    "legs",
    "slope",
    "order",
    "structure",
    "tray",
    "train",
    "spy",
    "sand",
    "celery",
    "market",
    "roll",
    "discussion",
    "competition",
    "roof",
    "hate",
    "crime",
    "head",
    "cough",
    "alarm",
    "rabbit",
    "truck",
    "waste",
    "tramp",
    "swim",
    "pies",
    "sea",
    "point",
    "record",
    "field",
    "honey",
    "song",
    "minute",
    "part",
    "authority",
    "bag",
    "aunt",
    "crate",
    "copper",
    "toothbrush",
    "baseball",
    "surprise",
    "breath",
    "mass",
    "road",
    "quarter",
    "government",
    "door",
    "suit",
    "teeth",
    "horse",
    "giants",
    "cellar",
    "muscle",
    "insurance",
    "bulb",
    "building",
    "plate",
    "wire",
    "cakes",
    "industry",
    "fowl",
    "reason",
    "error",
    "place",
    "actor",
    "shape",
    "dress",
    "substance",
    "sneeze",
    "cave",
    "art",
    "cent",
    "effect",
    "talk",
    "death",
    "thread",
    "end",
    "ladybug",
    "exchange",
    "question",
    "juice",
    "yard",
    "hall",
    "look",
    "ring",
    "soda",
    "boy",
    "ship",
    "tongue",
    "quilt",
    "pail",
    "shirt",
    "hope",
    "tree",
    "range",
    "idea",
    "shoes",
    "vegetable",
    "wealth",
    "bubble",
    "knee",
    "friends",
    "lunch",
    "collar",
    "home",
    "flowers",
    "taste",
    "behavior",
    "approval",
    "man",
    "winter",
    "throne",
    "kick",
    "governor",
    "riddle",
    "linen",
    "foot",
    "north",
    "stick",
    "grip",
    "brass",
    "eye",
    "trucks",
    "snakes",
    "wash",
    "pets",
    "system",
    "kitty",
    "apparatus",
    "carriage",
    "pin",
    "boot",
    "apparel",
    "floor",
    "side",
    "rat",
    "rain",
    "lettuce",
    "visitor",
    "slave",
    "rub",
    "dogs",
    "crown",
    "middle",
    "ball",
    "sign",
    "giraffe",
    "toy",
    "fang",
    "frame",
    "division",
    "crook",
    "button",
    "scene",
    "shop",
    "rod",
    "afterthought",
    "men",
    "popcorn",
    "care",
    "son",
    "library",
    "debt",
    "sound",
    "dad",
    "worm",
    "hill",
    "servant",
    "zebra",
    "channel",
    "price",
    "silver",
    "border",
    "twig",
    "harmony",
    "squirrel",
    "pigs",
    "scissors",
    "cushion",
    "ticket",
    "calendar",
    "seed",
    "rate",
    "verse",
    "station",
    "lumber",
    "screw",
    "chalk",
    "poison",
    "hour",
    "stop",
    "shock",
    "profit",
    "wave",
    "power",
    "eggnog",
    "voyage",
    "pipe",
    "trip",
    "tank",
    "position",
    "partner",
    "gate",
    "frog",
    "drawer",
    "treatment",
    "mitten",
    "example",
    "icicle",
    "space",
    "store",
    "distance",
    "holiday",
    "existence",
    "shoe",
    "plant",
    "woman",
    "driving",
    "cemetery",
    "bone",
    "bite",
    "guitar",
    "salt",
    "coach",
    "ray",
    "account",
    "beds",
    "vein",
    "note",
    "glove",
    "hot",
    "key",
    "sheet",
    "step",
    "school",
    "comparison",
    "adjustment",
    "hole",
    "experience",
    "hydrant",
    "jeans",
    "milk",
    "spade",
    "harbor",
    "bike",
    "scarf",
    "health",
    "activity",
    "steam",
    "guide",
    "orange",
    "mind",
    "nation",
    "girls",
    "stomach",
    "jelly",
    "shake",
    "island",
    "back",
    "test",
    "letters",
    "robin",
    "scent",
    "table",
    "vacation",
    "trousers",
    "lamp",
    "oven",
    "carpenter",
    "attack",
    "church",
    "appliance",
    "wilderness",
    "prose",
    "quiet",
    "cub",
    "country",
    "balance",
    "request",
    "cook",
    "zinc",
    "crow",
    "bottle",
    "cats",
    "hand",
    "burst",
    "flesh",
    "bell",
    "crayon",
    "limit",
    "fall",
    "flame",
    "name",
    "rings",
    "umbrella",
    "yak",
    "iron",
    "night",
    "territory",
    "bed",
    "level",
    "business",
    "water",
    "queen",
    "receipt",
    "aftermath",
    "morning",
    "vest",
    "instrument",
    "beginner",
    "agreement",
    "ink",
    "design",
    "battle",
    "tiger",
    "porter",
    "magic",
    "snake",
    "boat",
    "rest",
    "paper",
    "finger",
    "jail",
    "chickens",
    "leather",
    "trains",
    "spring",
    "support",
    "eyes",
    "sense",
    "stocking",
    "unit",
    "fold",
    "glass",
    "pan",
    "stitch",
    "turkey",
    "cup",
    "railway",
    "ants",
    "scarecrow",
    "pump",
    "change",
    "jewel",
    "connection",
    "animal",
    "finger",
    "science",
    "ground",
    "engine",
    "earth",
    "income",
    "berry",
    "statement",
    "control",
    "selection",
    "skirt",
    "cherry",
    "star",
    "invention",
    "quince",
    "babies",
    "language",
    "suggestion",
    "walk",
    "angle",
    "offer",
    "rail",
    "wrench",
    "things",
    "creature",
    "quicksand",
    "low",
    "frogs",
    "rifle",
    "view",
    "underwear",
    "trail",
    "pet",
    "amusement",
    "steel",
    "motion",
    "spark",
    "jar",
    "clover",
    "sugar",
    "pancake",
    "cactus",
    "haircut",
    "snail",
    "bit",
    "curtain",
    "cable",
    "join",
    "dog",
    "meat",
    "front",
    "rock",
    "toad",
    "face",
    "swing",
    "smash",
    "money",
    "thumb",
    "dock",
    "value",
    "day",
    "jump",
    "blade",
    "interest",
    "whistle",
    "river",
    "self",
    "pig",
    "increase",
    "use",
    "card",
    "group",
    "zoo",
    "parcel",
    "daughter",
    "protest",
    "coal",
    "kettle",
    "gold",
    "tax",
    "pen",
    "gun",
    "flag",
    "donkey",
    "grape",
    "stone",
    "book",
    "notebook",
    "grass",
    "cart",
    "wind",
    "rake",
    "liquid",
    "writer",
    "quartz",
    "chess"
]

//shift + alt + ->
//shft + fn + Home,End